In [1]:
import pandas as pd
import implicit
from sklearn.model_selection import train_test_split
import scipy.sparse as sparse
from pandas.api.types import CategoricalDtype 
import numpy as np
import warnings
from sklearn.metrics import average_precision_score

warnings.filterwarnings("ignore", category=UserWarning)

## Задание 1. Создание user-item-матрицы и разбиение данных на тест и контроль результатов

In [2]:
# Загрузка данных
ratings = pd.read_csv('ratings.csv')
ratings

         user_id  book_id  rating
0              1      258       5
1              2     4081       4
2              2      260       5
3              2     9296       5
4              2     2318       3
...          ...      ...     ...
5976474    49925      510       5
5976475    49925      528       4
5976476    49925      722       4
5976477    49925      949       5
5976478    49925     1023       4

[5976479 rows x 3 columns]

In [3]:
# Преобразование рейтингов в бинарные оценки
# Будем считать, если оценка больше 4, то книга понравилась
ratings['rating'] = ratings['rating'].apply(lambda x: 1 if x > 4 else 0)

In [4]:
# Пронумеруйте для каждого пользователя его прочитанные книги согласно расположению книг по порядку
ratings['book_order'] = ratings.groupby('user_id')['book_id'].rank(method='first')

In [5]:
# Переведите номера прочитанных книг в доли по формуле «порядковый номер / общее количество прочитанных пользователем книг»
ratings['book_order_ratio'] = ratings['book_order'] / ratings.groupby('user_id')['book_id'].transform('count')

In [6]:
ratings

         user_id  book_id  rating  book_order  book_order_ratio
0              1      258       1        63.0          0.538462
1              2     4081       0        54.0          0.830769
2              2      260       1        30.0          0.461538
3              2     9296       1        63.0          0.969231
4              2     2318       0        48.0          0.738462
...          ...      ...     ...         ...               ...
5976474    49925      510       1        41.0          0.303704
5976475    49925      528       0        42.0          0.311111
5976476    49925      722       0        45.0          0.333333
5976477    49925      949       1        51.0          0.377778
5976478    49925     1023       0        52.0          0.385185

[5976479 rows x 5 columns]

In [7]:
# Разделите данные на обучение и контроль
train, test = train_test_split(ratings, train_size=0.8, random_state=42, shuffle=False)

In [8]:
# Построение user-item-матрицы
train_user_index = train.user_id.unique()
train_book_index = train.book_id.unique()
test_user_index = test.user_id.unique()
test_book_index = test.book_id.unique()

rows = train['user_id'].astype(pd.CategoricalDtype(categories=train_user_index)).cat.codes
cols = train['book_id'].astype(pd.CategoricalDtype(categories=train_book_index)).cat.codes
train_matrix = sparse.csr_matrix((train.rating, (rows, cols)), shape=(len(train_user_index), len(train_book_index)))

rows = test['user_id'].astype(pd.CategoricalDtype(categories=test_user_index)).cat.codes
cols = test['book_id'].astype(pd.CategoricalDtype(categories=test_book_index)).cat.codes
test_matrix = sparse.csr_matrix((test.rating, (rows, cols)), shape=(len(test_user_index), len(test_book_index)))

In [9]:
train_matrix = train_matrix.toarray()
test_matrix = test_matrix.toarray()

In [10]:
# Проверка размеров матриц
if train_matrix.shape[0] == len(train_user_index):
    print(f"Количество строк в обучающей матрице ({train_matrix.shape[0]}) РАВНО Количеству уникальных пользователей ({len(train_user_index)})")
else:
    print(f"Ошибка! Количество строк в обучающей матрице ({train_matrix.shape[0]}) НЕ РАВНО Количеству уникальных пользователей ({len(train_user_index)})")

if train_matrix.shape[1] == len(train_book_index):
    print(f"Количество столбцов в обучающей матрице ({train_matrix.shape[1]}) РАВНО Количеству уникальных книг ({len(train_book_index)})")
else:
    print(f"Ошибка! Количество столбцов в обучающей матрице ({train_matrix.shape[1]}) НЕ РАВНО Количеству уникальных книг ({len(train_book_index)})")

if test_matrix.shape[0] == len(test_user_index):
    print(f"Количество строк в тестовой матрице ({test_matrix.shape[0]}) РАВНО Количеству уникальных пользователей ({len(test_user_index)})")
else:
    print(f"Ошибка! Количество строк в тестовой матрице ({test_matrix.shape[0]}) НЕ РАВНО Количеству уникальных пользователей ({len(test_user_index)})")

if test_matrix.shape[1] == len(test_book_index):
    print(f"Количество столбцов в тестовой матрице ({test_matrix.shape[1]}) РАВНО Количеству уникальных книг ({len(test_book_index)})")
else:
    print(f"Ошибка! Количество столбцов в тестовой матрице ({test_matrix.shape[1]}) НЕ РАВНО Количеству уникальных книг ({len(test_book_index)})")

Количество строк в обучающей матрице (48769) РАВНО Количеству уникальных пользователей (48769)
Количество столбцов в обучающей матрице (9693) РАВНО Количеству уникальных книг (9693)
Количество строк в тестовой матрице (32281) РАВНО Количеству уникальных пользователей (32281)
Количество столбцов в тестовой матрице (9999) РАВНО Количеству уникальных книг (9999)

In [39]:
# Вывод списка названий книг с высокой оценкой для любого из пользователей
# Для удобства возьмем 2-го пользователя из списка
user_index = 2

In [12]:
user_id = train_user_index[user_index]
print(f"Cписок названий книг с высокой оценкой для пользователя {user_id}:")
for ind, score in enumerate(train_matrix[user_index]):
    if score>0:
        book_id = train_book_index[ind] 
        print(f'book_id={book_id}, score={score}')

Cписок названий книг с высокой оценкой для пользователя 4:
book_id=18, score=1
book_id=27, score=1
book_id=21, score=1
book_id=2, score=1
book_id=23, score=1
book_id=24, score=1
book_id=103, score=1
book_id=35, score=1
book_id=325, score=1
book_id=1237, score=1
book_id=36, score=1
book_id=102, score=1
book_id=693, score=1
book_id=87, score=1
book_id=42, score=1
book_id=245, score=1
book_id=81, score=1
book_id=10, score=1
book_id=497, score=1
book_id=489, score=1
book_id=1380, score=1
book_id=3469, score=1
book_id=85, score=1
book_id=321, score=1
book_id=93, score=1
book_id=383, score=1
book_id=1210, score=1
book_id=879, score=1
book_id=265, score=1
book_id=25, score=1
book_id=8464, score=1

## Задание 2. Создание бейзлайнов и расчёт метрик

In [13]:
def ap_at_k(recommendations, true_positives, k=10):
    """
    Подсчитывает метрику AP@K.

    Args:
        recommendations: Список рекомендаций (book_id).
        true_positives: Список книг, положительно оценённых пользователем.
        k: Количество рекомендаций, которые учитываются при подсчёте метрики.

    Returns:
        Значение метрики AP@K.
    """
    
    # Отрезаем список рекомендаций до k элементов
    recommendations = recommendations[:k]
    
    # Создаем список бинарных меток (1 - книга в рекомендациях есть в списке положительно оцененных, 0 - нет)
    y_true = [1 if book_ind in true_positives else 0 for book_ind in recommendations]
    
    # Используем sklearn.metrics.average_precision_score для подсчета AP@K
    ap = average_precision_score(y_true, [1]*len(y_true)) 
    
    return ap

### Случайный бейзлайн

In [21]:
random_users_inds = np.random.choice(len(train_user_index), size=500, replace=False)
random_baseline_map10 = []

In [22]:
# Получаем список книг, которые пользователь уже прочитал
already_read = []  # Создаем словарь для хранения уже прочитанных книг
  
for rand_user_ind in random_users_inds:
    user_id = train_user_index[rand_user_ind]  # Получаем user_id
    already_read = train_book_index[np.where(train_matrix[rand_user_ind] >= 0)[0]].tolist()  # Получаем все прочитанные книги 
    # Генерируем случайный список из 20 книг
    random_recommendations = np.random.choice(len(train_book_index), size=20, replace=False)
    # Удаляем книги, которые пользователь уже прочитал
    unique_recommendations = list(set(random_recommendations) - set(already_read))
    unique_recommendations = train_book_index[unique_recommendations].tolist()
 
    # Получаем список книг, которые пользователь положительно оценил
    true_positives = test.loc[(test.user_id == user_id) & (test.rating == 1), 'book_id'].tolist()
     
    if unique_recommendations and true_positives: # Проверка на наличие положительных оценок
        # Вычисляем AP@10
        ap10 = ap_at_k(unique_recommendations, true_positives, k=10)
        random_baseline_map10.append(ap10)
    else:
        if not true_positives:
            print(f"Пользователь {user_id} не имеет положительных оценок в тестовой выборке!")
        else:
            print(f"Пользователь {user_id} уже прочитал все книги или не имеет положительных оценок в тестовой выборке!")

Пользователь 13756 не имеет положительных оценок в тестовой выборке!
Пользователь 5422 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 13437 не имеет положительных оценок в тестовой выборке!
Пользователь 41734 не имеет положительных оценок в тестовой выборке!
Пользователь 25215 не имеет положительных оценок в тестовой выборке!
Пользователь 31746 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 40075 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 21841 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 36964 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 30558 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 14334 не имеет положительных оценок в тестовой выборке!
Пользователь 8351 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 27585 не имеет положительных оценок в тестовой выборке!
Пользователь 40898 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 39451 не имеет положительных оценок в тестовой выборке!
Пользователь 25597 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15265 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 45706 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 20516 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 48131 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 13028 не имеет положительных оценок в тестовой выборке!
Пользователь 37688 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 28459 не имеет положительных оценок в тестовой выборке!
Пользователь 45679 не имеет положительных оценок в тестовой выборке!
Пользователь 39181 не имеет положительных оценок в тестовой выборке!
Пользователь 33969 не имеет положительных оценок в тестовой выборке!
Пользователь 29534 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 48372 не имеет положительных оценок в тестовой выборке!
Пользователь 8214 не имеет положительных оценок в тестовой выборке!
Пользователь 9723 не имеет положительных оценок в тестовой выборке!
Пользователь 48661 не имеет положительных оценок в тестовой выборке!
Пользователь 25606 не имеет положительных оценок в тестовой выборке!
Пользователь 5243 не имеет положительных оценок в тестовой выборке!
Пользователь 22042 не имеет положительных оценок в тестовой выборке!
Пользователь 47821 не имеет положительных оценок в тестовой выборке!
Пользователь 50282 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 7124 не имеет положительных оценок в тестовой выборке!
Пользователь 44242 не имеет положительных оценок в тестовой выборке!
Пользователь 13542 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15772 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 5289 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 41493 не имеет положительных оценок в тестовой выборке!
Пользователь 19400 не имеет положительных оценок в тестовой выборке!
Пользователь 26277 не имеет положительных оценок в тестовой выборке!
Пользователь 3707 не имеет положительных оценок в тестовой выборке!
Пользователь 6420 не имеет положительных оценок в тестовой выборке!
Пользователь 8070 не имеет положительных оценок в тестовой выборке!
Пользователь 34665 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 38907 не имеет положительных оценок в тестовой выборке!
Пользователь 6979 не имеет положительных оценок в тестовой выборке!
Пользователь 376 не имеет положительных оценок в тестовой выборке!
Пользователь 21144 не имеет положительных оценок в тестовой выборке!
Пользователь 36059 не имеет положительных оценок в тестовой выборке!
Пользователь 9361 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 2515 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 24361 не имеет положительных оценок в тестовой выборке!
Пользователь 29437 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 38274 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 30764 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 4989 не имеет положительных оценок в тестовой выборке!
Пользователь 26320 не имеет положительных оценок в тестовой выборке!
Пользователь 17635 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 29936 не имеет положительных оценок в тестовой выборке!
Пользователь 33899 не имеет положительных оценок в тестовой выборке!
Пользователь 20374 не имеет положительных оценок в тестовой выборке!
Пользователь 7458 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 13482 не имеет положительных оценок в тестовой выборке!
Пользователь 27792 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 1187 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15492 не имеет положительных оценок в тестовой выборке!
Пользователь 25650 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 28940 не имеет положительных оценок в тестовой выборке!
Пользователь 15591 не имеет положительных оценок в тестовой выборке!
Пользователь 32190 не имеет положительных оценок в тестовой выборке!
Пользователь 28696 не имеет положительных оценок в тестовой выборке!
Пользователь 41682 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 41805 не имеет положительных оценок в тестовой выборке!
Пользователь 13128 не имеет положительных оценок в тестовой выборке!
Пользователь 4723 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 24282 не имеет положительных оценок в тестовой выборке!
Пользователь 35644 не имеет положительных оценок в тестовой выборке!
Пользователь 29503 не имеет положительных оценок в тестовой выборке!
Пользователь 24218 не имеет положительных оценок в тестовой выборке!
Пользователь 48759 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 20874 не имеет положительных оценок в тестовой выборке!
Пользователь 25198 не имеет положительных оценок в тестовой выборке!
Пользователь 15502 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 38287 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 16810 не имеет положительных оценок в тестовой выборке!
Пользователь 45528 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 6000 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 41130 не имеет положительных оценок в тестовой выборке!
Пользователь 6498 не имеет положительных оценок в тестовой выборке!
Пользователь 10538 не имеет положительных оценок в тестовой выборке!
Пользователь 10336 не имеет положительных оценок в тестовой выборке!
Пользователь 40157 не имеет положительных оценок в тестовой выборке!
Пользователь 42347 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 30169 не имеет положительных оценок в тестовой выборке!
Пользователь 38737 не имеет положительных оценок в тестовой выборке!
Пользователь 11144 не имеет положительных оценок в тестовой выборке!
Пользователь 39837 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15630 не имеет положительных оценок в тестовой выборке!
Пользователь 15195 не имеет положительных оценок в тестовой выборке!
Пользователь 7128 не имеет положительных оценок в тестовой выборке!
Пользователь 43785 не имеет положительных оценок в тестовой выборке!
Пользователь 37074 не имеет положительных оценок в тестовой выборке!
Пользователь 726 не имеет положительных оценок в тестовой выборке!
Пользователь 1595 не имеет положительных оценок в тестовой выборке!
Пользователь 25635 не имеет положительных оценок в тестовой выборке!
Пользователь 49154 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 18861 не имеет положительных оценок в тестовой выборке!
Пользователь 48493 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 40054 не имеет положительных оценок в тестовой выборке!
Пользователь 14161 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 33544 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 40987 не имеет положительных оценок в тестовой выборке!
Пользователь 40693 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 28043 не имеет положительных оценок в тестовой выборке!
Пользователь 20436 не имеет положительных оценок в тестовой выборке!
Пользователь 48690 не имеет положительных оценок в тестовой выборке!
Пользователь 7344 не имеет положительных оценок в тестовой выборке!
Пользователь 21443 не имеет положительных оценок в тестовой выборке!
Пользователь 43081 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 34284 не имеет положительных оценок в тестовой выборке!
Пользователь 1308 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 34905 не имеет положительных оценок в тестовой выборке!
Пользователь 14674 не имеет положительных оценок в тестовой выборке!
Пользователь 44190 не имеет положительных оценок в тестовой выборке!
Пользователь 16719 не имеет положительных оценок в тестовой выборке!
Пользователь 8648 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 45374 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 22444 не имеет положительных оценок в тестовой выборке!
Пользователь 18838 не имеет положительных оценок в тестовой выборке!
Пользователь 14354 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 25193 не имеет положительных оценок в тестовой выборке!
Пользователь 6277 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 19104 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 45520 не имеет положительных оценок в тестовой выборке!
Пользователь 15926 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 29485 не имеет положительных оценок в тестовой выборке!
Пользователь 20766 не имеет положительных оценок в тестовой выборке!
Пользователь 40834 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 25500 не имеет положительных оценок в тестовой выборке!
Пользователь 26852 не имеет положительных оценок в тестовой выборке!
Пользователь 31272 не имеет положительных оценок в тестовой выборке!
Пользователь 9890 не имеет положительных оценок в тестовой выборке!
Пользователь 34809 не имеет положительных оценок в тестовой выборке!
Пользователь 508 не имеет положительных оценок в тестовой выборке!
Пользователь 15327 не имеет положительных оценок в тестовой выборке!
Пользователь 30122 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 27859 не имеет положительных оценок в тестовой выборке!
Пользователь 26221 не имеет положительных оценок в тестовой выборке!
Пользователь 37564 не имеет положительных оценок в тестовой выборке!
Пользователь 2068 не имеет положительных оценок в тестовой выборке!
Пользователь 796 не имеет положительных оценок в тестовой выборке!
Пользователь 30655 не имеет положительных оценок в тестовой выборке!
Пользователь 22661 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15600 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 48627 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 45498 не имеет положительных оценок в тестовой выборке!
Пользователь 47031 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 41738 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 30036 не имеет положительных оценок в тестовой выборке!
Пользователь 8328 не имеет положительных оценок в тестовой выборке!
Пользователь 17408 не имеет положительных оценок в тестовой выборке!
Пользователь 7009 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 22735 не имеет положительных оценок в тестовой выборке!
Пользователь 25466 не имеет положительных оценок в тестовой выборке!
Пользователь 31052 не имеет положительных оценок в тестовой выборке!
Пользователь 2689 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 38211 не имеет положительных оценок в тестовой выборке!
Пользователь 19538 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 23730 не имеет положительных оценок в тестовой выборке!
Пользователь 22988 не имеет положительных оценок в тестовой выборке!
Пользователь 311 не имеет положительных оценок в тестовой выборке!
Пользователь 7978 не имеет положительных оценок в тестовой выборке!
Пользователь 18380 не имеет положительных оценок в тестовой выборке!
Пользователь 44677 не имеет положительных оценок в тестовой выборке!
Пользователь 22677 не имеет положительных оценок в тестовой выборке!
Пользователь 14097 не имеет положительных оценок в тестовой выборке!
Пользователь 33621 не имеет положительных оценок в тестовой выборке!
Пользователь 38505 не имеет положительных оценок в тестовой выборке!
Пользователь 39588 не имеет положительных оценок в тестовой выборке!
Пользователь 8459 не имеет положительных оценок в тестовой выборке!
Пользователь 9525 не имеет положительных оценок в тестовой выборке!
Пользователь 12545 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 1748 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 39509 не имеет положительных оценок в тестовой выборке!
Пользователь 6879 не имеет положительных оценок в тестовой выборке!
Пользователь 50195 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 7809 не имеет положительных оценок в тестовой выборке!
Пользователь 21325 не имеет положительных оценок в тестовой выборке!
Пользователь 18326 не имеет положительных оценок в тестовой выборке!
Пользователь 32566 не имеет положительных оценок в тестовой выборке!
Пользователь 6314 не имеет положительных оценок в тестовой выборке!
Пользователь 45344 не имеет положительных оценок в тестовой выборке!
Пользователь 21426 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 34501 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 24940 не имеет положительных оценок в тестовой выборке!
Пользователь 1248 не имеет положительных оценок в тестовой выборке!
Пользователь 17187 не имеет положительных оценок в тестовой выборке!
Пользователь 47889 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 19256 не имеет положительных оценок в тестовой выборке!
Пользователь 27545 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 18803 не имеет положительных оценок в тестовой выборке!
Пользователь 42236 не имеет положительных оценок в тестовой выборке!
Пользователь 44518 не имеет положительных оценок в тестовой выборке!
Пользователь 10012 не имеет положительных оценок в тестовой выборке!
Пользователь 29493 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 23417 не имеет положительных оценок в тестовой выборке!
Пользователь 23964 не имеет положительных оценок в тестовой выборке!
Пользователь 40142 не имеет положительных оценок в тестовой выборке!
Пользователь 23081 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 46836 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 17282 не имеет положительных оценок в тестовой выборке!
Пользователь 18889 не имеет положительных оценок в тестовой выборке!
Пользователь 27625 не имеет положительных оценок в тестовой выборке!
Пользователь 47162 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 46928 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 14949 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 9261 не имеет положительных оценок в тестовой выборке!
Пользователь 48407 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 10202 не имеет положительных оценок в тестовой выборке!
Пользователь 2521 не имеет положительных оценок в тестовой выборке!
Пользователь 28787 не имеет положительных оценок в тестовой выборке!
Пользователь 26766 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 23790 не имеет положительных оценок в тестовой выборке!
Пользователь 24301 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 1503 не имеет положительных оценок в тестовой выборке!
Пользователь 50272 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 41547 не имеет положительных оценок в тестовой выборке!
Пользователь 26139 не имеет положительных оценок в тестовой выборке!
Пользователь 19583 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 7408 не имеет положительных оценок в тестовой выборке!
Пользователь 24247 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 4392 не имеет положительных оценок в тестовой выборке!
Пользователь 18128 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 31270 не имеет положительных оценок в тестовой выборке!
Пользователь 34264 не имеет положительных оценок в тестовой выборке!
Пользователь 15164 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 9420 не имеет положительных оценок в тестовой выборке!
Пользователь 34112 не имеет положительных оценок в тестовой выборке!
Пользователь 18037 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 48625 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 24389 не имеет положительных оценок в тестовой выборке!
Пользователь 38398 не имеет положительных оценок в тестовой выборке!
Пользователь 11027 не имеет положительных оценок в тестовой выборке!
Пользователь 46305 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 15483 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 12249 не имеет положительных оценок в тестовой выборке!
Пользователь 27483 не имеет положительных оценок в тестовой выборке!
Пользователь 40296 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!
Пользователь 9586 не имеет положительных оценок в тестовой выборке!
Пользователь 9214 не имеет положительных оценок в тестовой выборке!
Пользователь 18419 уже прочитал все книги или не имеет положительных оценок в тестовой выборке!

In [23]:
# Среднее значение AP@10
mean_ap_at_10 = np.mean(random_baseline_map10)
print(f"Среднее значение AP@10: {mean_ap_at_10}")

Среднее значение AP@10: 0.0

### Бейзлайн из самых популярных книг

In [19]:
popularity_counts = train.groupby('book_id').size()
top_popular_books = popularity_counts.nlargest(20).index.tolist()

popular_baseline_map10 = []
for rand_user_ind in random_users_inds:
    user_id = train_user_index[rand_user_ind]
    true_positives = test.loc[(test.user_id == user_id) & (test.rating == 1), 'book_id'].tolist()

    if true_positives:
        ap10 = ap_at_k(top_popular_books, true_positives, k=10)
        popular_baseline_map10.append(ap10)
    else:
        print(f"Пользователь {user_id} не имеет положительных оценок в тестовой выборке!")

Пользователь 16628 не имеет положительных оценок в тестовой выборке!
Пользователь 30302 не имеет положительных оценок в тестовой выборке!
Пользователь 4259 не имеет положительных оценок в тестовой выборке!
Пользователь 25082 не имеет положительных оценок в тестовой выборке!
Пользователь 38842 не имеет положительных оценок в тестовой выборке!
Пользователь 3168 не имеет положительных оценок в тестовой выборке!
Пользователь 16132 не имеет положительных оценок в тестовой выборке!
Пользователь 27192 не имеет положительных оценок в тестовой выборке!
Пользователь 40981 не имеет положительных оценок в тестовой выборке!
Пользователь 13310 не имеет положительных оценок в тестовой выборке!
Пользователь 9840 не имеет положительных оценок в тестовой выборке!
Пользователь 324 не имеет положительных оценок в тестовой выборке!
Пользователь 220 не имеет положительных оценок в тестовой выборке!
Пользователь 10376 не имеет положительных оценок в тестовой выборке!
Пользователь 46219 не имеет положительных оценок в тестовой выборке!
Пользователь 23100 не имеет положительных оценок в тестовой выборке!
Пользователь 13493 не имеет положительных оценок в тестовой выборке!
Пользователь 18527 не имеет положительных оценок в тестовой выборке!
Пользователь 36529 не имеет положительных оценок в тестовой выборке!
Пользователь 7931 не имеет положительных оценок в тестовой выборке!
Пользователь 47370 не имеет положительных оценок в тестовой выборке!
Пользователь 31609 не имеет положительных оценок в тестовой выборке!
Пользователь 1854 не имеет положительных оценок в тестовой выборке!
Пользователь 33177 не имеет положительных оценок в тестовой выборке!
Пользователь 5956 не имеет положительных оценок в тестовой выборке!
Пользователь 17128 не имеет положительных оценок в тестовой выборке!
Пользователь 49350 не имеет положительных оценок в тестовой выборке!
Пользователь 8005 не имеет положительных оценок в тестовой выборке!
Пользователь 32147 не имеет положительных оценок в тестовой выборке!
Пользователь 41387 не имеет положительных оценок в тестовой выборке!
Пользователь 29598 не имеет положительных оценок в тестовой выборке!
Пользователь 1375 не имеет положительных оценок в тестовой выборке!
Пользователь 19016 не имеет положительных оценок в тестовой выборке!
Пользователь 36518 не имеет положительных оценок в тестовой выборке!
Пользователь 40235 не имеет положительных оценок в тестовой выборке!
Пользователь 45542 не имеет положительных оценок в тестовой выборке!
Пользователь 26489 не имеет положительных оценок в тестовой выборке!
Пользователь 41035 не имеет положительных оценок в тестовой выборке!
Пользователь 39865 не имеет положительных оценок в тестовой выборке!
Пользователь 10343 не имеет положительных оценок в тестовой выборке!
Пользователь 7646 не имеет положительных оценок в тестовой выборке!
Пользователь 14868 не имеет положительных оценок в тестовой выборке!
Пользователь 4490 не имеет положительных оценок в тестовой выборке!
Пользователь 8278 не имеет положительных оценок в тестовой выборке!
Пользователь 30275 не имеет положительных оценок в тестовой выборке!
Пользователь 29108 не имеет положительных оценок в тестовой выборке!
Пользователь 49990 не имеет положительных оценок в тестовой выборке!
Пользователь 3927 не имеет положительных оценок в тестовой выборке!
Пользователь 32314 не имеет положительных оценок в тестовой выборке!
Пользователь 38143 не имеет положительных оценок в тестовой выборке!
Пользователь 20740 не имеет положительных оценок в тестовой выборке!
Пользователь 31286 не имеет положительных оценок в тестовой выборке!
Пользователь 13158 не имеет положительных оценок в тестовой выборке!
Пользователь 15857 не имеет положительных оценок в тестовой выборке!
Пользователь 21508 не имеет положительных оценок в тестовой выборке!
Пользователь 23242 не имеет положительных оценок в тестовой выборке!
Пользователь 25017 не имеет положительных оценок в тестовой выборке!
Пользователь 21348 не имеет положительных оценок в тестовой выборке!
Пользователь 18356 не имеет положительных оценок в тестовой выборке!
Пользователь 48592 не имеет положительных оценок в тестовой выборке!
Пользователь 48006 не имеет положительных оценок в тестовой выборке!
Пользователь 20088 не имеет положительных оценок в тестовой выборке!
Пользователь 11554 не имеет положительных оценок в тестовой выборке!
Пользователь 10624 не имеет положительных оценок в тестовой выборке!
Пользователь 43019 не имеет положительных оценок в тестовой выборке!
Пользователь 42373 не имеет положительных оценок в тестовой выборке!
Пользователь 13009 не имеет положительных оценок в тестовой выборке!
Пользователь 37635 не имеет положительных оценок в тестовой выборке!
Пользователь 16959 не имеет положительных оценок в тестовой выборке!
Пользователь 6584 не имеет положительных оценок в тестовой выборке!
Пользователь 30838 не имеет положительных оценок в тестовой выборке!
Пользователь 48248 не имеет положительных оценок в тестовой выборке!
Пользователь 12574 не имеет положительных оценок в тестовой выборке!
Пользователь 20878 не имеет положительных оценок в тестовой выборке!
Пользователь 38897 не имеет положительных оценок в тестовой выборке!
Пользователь 32819 не имеет положительных оценок в тестовой выборке!
Пользователь 10548 не имеет положительных оценок в тестовой выборке!
Пользователь 9557 не имеет положительных оценок в тестовой выборке!
Пользователь 11550 не имеет положительных оценок в тестовой выборке!
Пользователь 14797 не имеет положительных оценок в тестовой выборке!
Пользователь 4859 не имеет положительных оценок в тестовой выборке!
Пользователь 45214 не имеет положительных оценок в тестовой выборке!
Пользователь 39516 не имеет положительных оценок в тестовой выборке!
Пользователь 17859 не имеет положительных оценок в тестовой выборке!
Пользователь 19014 не имеет положительных оценок в тестовой выборке!
Пользователь 32795 не имеет положительных оценок в тестовой выборке!
Пользователь 29831 не имеет положительных оценок в тестовой выборке!
Пользователь 34763 не имеет положительных оценок в тестовой выборке!
Пользователь 30582 не имеет положительных оценок в тестовой выборке!
Пользователь 20587 не имеет положительных оценок в тестовой выборке!
Пользователь 42161 не имеет положительных оценок в тестовой выборке!
Пользователь 7369 не имеет положительных оценок в тестовой выборке!
Пользователь 15170 не имеет положительных оценок в тестовой выборке!
Пользователь 4817 не имеет положительных оценок в тестовой выборке!
Пользователь 36575 не имеет положительных оценок в тестовой выборке!
Пользователь 13338 не имеет положительных оценок в тестовой выборке!
Пользователь 25590 не имеет положительных оценок в тестовой выборке!
Пользователь 23476 не имеет положительных оценок в тестовой выборке!
Пользователь 13252 не имеет положительных оценок в тестовой выборке!
Пользователь 3597 не имеет положительных оценок в тестовой выборке!
Пользователь 1014 не имеет положительных оценок в тестовой выборке!
Пользователь 32915 не имеет положительных оценок в тестовой выборке!
Пользователь 16501 не имеет положительных оценок в тестовой выборке!
Пользователь 22349 не имеет положительных оценок в тестовой выборке!
Пользователь 30412 не имеет положительных оценок в тестовой выборке!
Пользователь 4516 не имеет положительных оценок в тестовой выборке!
Пользователь 25016 не имеет положительных оценок в тестовой выборке!
Пользователь 13143 не имеет положительных оценок в тестовой выборке!
Пользователь 20411 не имеет положительных оценок в тестовой выборке!
Пользователь 20405 не имеет положительных оценок в тестовой выборке!
Пользователь 3228 не имеет положительных оценок в тестовой выборке!
Пользователь 2239 не имеет положительных оценок в тестовой выборке!
Пользователь 43732 не имеет положительных оценок в тестовой выборке!
Пользователь 9136 не имеет положительных оценок в тестовой выборке!
Пользователь 31118 не имеет положительных оценок в тестовой выборке!
Пользователь 39517 не имеет положительных оценок в тестовой выборке!
Пользователь 17011 не имеет положительных оценок в тестовой выборке!
Пользователь 25059 не имеет положительных оценок в тестовой выборке!
Пользователь 38516 не имеет положительных оценок в тестовой выборке!
Пользователь 44369 не имеет положительных оценок в тестовой выборке!
Пользователь 18095 не имеет положительных оценок в тестовой выборке!
Пользователь 43662 не имеет положительных оценок в тестовой выборке!
Пользователь 6395 не имеет положительных оценок в тестовой выборке!
Пользователь 15430 не имеет положительных оценок в тестовой выборке!
Пользователь 5074 не имеет положительных оценок в тестовой выборке!
Пользователь 40562 не имеет положительных оценок в тестовой выборке!
Пользователь 30594 не имеет положительных оценок в тестовой выборке!
Пользователь 22209 не имеет положительных оценок в тестовой выборке!
Пользователь 40704 не имеет положительных оценок в тестовой выборке!
Пользователь 23736 не имеет положительных оценок в тестовой выборке!
Пользователь 22931 не имеет положительных оценок в тестовой выборке!
Пользователь 18755 не имеет положительных оценок в тестовой выборке!
Пользователь 25396 не имеет положительных оценок в тестовой выборке!
Пользователь 20091 не имеет положительных оценок в тестовой выборке!
Пользователь 24259 не имеет положительных оценок в тестовой выборке!
Пользователь 24399 не имеет положительных оценок в тестовой выборке!
Пользователь 45335 не имеет положительных оценок в тестовой выборке!
Пользователь 46606 не имеет положительных оценок в тестовой выборке!
Пользователь 24008 не имеет положительных оценок в тестовой выборке!
Пользователь 46059 не имеет положительных оценок в тестовой выборке!
Пользователь 12999 не имеет положительных оценок в тестовой выборке!
Пользователь 8822 не имеет положительных оценок в тестовой выборке!
Пользователь 2632 не имеет положительных оценок в тестовой выборке!
Пользователь 22574 не имеет положительных оценок в тестовой выборке!
Пользователь 30428 не имеет положительных оценок в тестовой выборке!
Пользователь 9032 не имеет положительных оценок в тестовой выборке!
Пользователь 2285 не имеет положительных оценок в тестовой выборке!
Пользователь 29916 не имеет положительных оценок в тестовой выборке!
Пользователь 599 не имеет положительных оценок в тестовой выборке!
Пользователь 10567 не имеет положительных оценок в тестовой выборке!
Пользователь 14138 не имеет положительных оценок в тестовой выборке!
Пользователь 7935 не имеет положительных оценок в тестовой выборке!
Пользователь 14022 не имеет положительных оценок в тестовой выборке!
Пользователь 31677 не имеет положительных оценок в тестовой выборке!
Пользователь 35093 не имеет положительных оценок в тестовой выборке!
Пользователь 34217 не имеет положительных оценок в тестовой выборке!
Пользователь 34903 не имеет положительных оценок в тестовой выборке!
Пользователь 13869 не имеет положительных оценок в тестовой выборке!
Пользователь 14077 не имеет положительных оценок в тестовой выборке!
Пользователь 24963 не имеет положительных оценок в тестовой выборке!
Пользователь 41565 не имеет положительных оценок в тестовой выборке!
Пользователь 36983 не имеет положительных оценок в тестовой выборке!
Пользователь 21477 не имеет положительных оценок в тестовой выборке!
Пользователь 34054 не имеет положительных оценок в тестовой выборке!
Пользователь 30601 не имеет положительных оценок в тестовой выборке!
Пользователь 37328 не имеет положительных оценок в тестовой выборке!
Пользователь 1433 не имеет положительных оценок в тестовой выборке!
Пользователь 2237 не имеет положительных оценок в тестовой выборке!
Пользователь 35039 не имеет положительных оценок в тестовой выборке!
Пользователь 31281 не имеет положительных оценок в тестовой выборке!
Пользователь 46810 не имеет положительных оценок в тестовой выборке!
Пользователь 1696 не имеет положительных оценок в тестовой выборке!
Пользователь 11903 не имеет положительных оценок в тестовой выборке!
Пользователь 33360 не имеет положительных оценок в тестовой выборке!
Пользователь 26615 не имеет положительных оценок в тестовой выборке!
Пользователь 269 не имеет положительных оценок в тестовой выборке!
Пользователь 447 не имеет положительных оценок в тестовой выборке!
Пользователь 16120 не имеет положительных оценок в тестовой выборке!
Пользователь 47422 не имеет положительных оценок в тестовой выборке!
Пользователь 7566 не имеет положительных оценок в тестовой выборке!
Пользователь 13186 не имеет положительных оценок в тестовой выборке!
Пользователь 17682 не имеет положительных оценок в тестовой выборке!
Пользователь 23260 не имеет положительных оценок в тестовой выборке!
Пользователь 23231 не имеет положительных оценок в тестовой выборке!
Пользователь 39120 не имеет положительных оценок в тестовой выборке!
Пользователь 1809 не имеет положительных оценок в тестовой выборке!
Пользователь 33975 не имеет положительных оценок в тестовой выборке!
Пользователь 16063 не имеет положительных оценок в тестовой выборке!
Пользователь 20907 не имеет положительных оценок в тестовой выборке!
Пользователь 39686 не имеет положительных оценок в тестовой выборке!
Пользователь 32906 не имеет положительных оценок в тестовой выборке!
Пользователь 8541 не имеет положительных оценок в тестовой выборке!
Пользователь 27607 не имеет положительных оценок в тестовой выборке!
Пользователь 22867 не имеет положительных оценок в тестовой выборке!
Пользователь 16426 не имеет положительных оценок в тестовой выборке!
Пользователь 44295 не имеет положительных оценок в тестовой выборке!
Пользователь 13187 не имеет положительных оценок в тестовой выборке!
Пользователь 22342 не имеет положительных оценок в тестовой выборке!
Пользователь 8288 не имеет положительных оценок в тестовой выборке!
Пользователь 2725 не имеет положительных оценок в тестовой выборке!
Пользователь 48207 не имеет положительных оценок в тестовой выборке!
Пользователь 12526 не имеет положительных оценок в тестовой выборке!
Пользователь 28169 не имеет положительных оценок в тестовой выборке!
Пользователь 40270 не имеет положительных оценок в тестовой выборке!
Пользователь 34080 не имеет положительных оценок в тестовой выборке!
Пользователь 41581 не имеет положительных оценок в тестовой выборке!
Пользователь 5743 не имеет положительных оценок в тестовой выборке!
Пользователь 37448 не имеет положительных оценок в тестовой выборке!
Пользователь 5663 не имеет положительных оценок в тестовой выборке!
Пользователь 5937 не имеет положительных оценок в тестовой выборке!
Пользователь 17076 не имеет положительных оценок в тестовой выборке!
Пользователь 16194 не имеет положительных оценок в тестовой выборке!
Пользователь 31826 не имеет положительных оценок в тестовой выборке!
Пользователь 39929 не имеет положительных оценок в тестовой выборке!
Пользователь 23582 не имеет положительных оценок в тестовой выборке!
Пользователь 36459 не имеет положительных оценок в тестовой выборке!
Пользователь 1956 не имеет положительных оценок в тестовой выборке!
Пользователь 16971 не имеет положительных оценок в тестовой выборке!
Пользователь 41736 не имеет положительных оценок в тестовой выборке!
Пользователь 27133 не имеет положительных оценок в тестовой выборке!
Пользователь 9406 не имеет положительных оценок в тестовой выборке!
Пользователь 36048 не имеет положительных оценок в тестовой выборке!
Пользователь 40520 не имеет положительных оценок в тестовой выборке!
Пользователь 19498 не имеет положительных оценок в тестовой выборке!
Пользователь 8558 не имеет положительных оценок в тестовой выборке!
Пользователь 44319 не имеет положительных оценок в тестовой выборке!
Пользователь 29457 не имеет положительных оценок в тестовой выборке!
Пользователь 6310 не имеет положительных оценок в тестовой выборке!
Пользователь 48246 не имеет положительных оценок в тестовой выборке!
Пользователь 7502 не имеет положительных оценок в тестовой выборке!
Пользователь 36423 не имеет положительных оценок в тестовой выборке!
Пользователь 20618 не имеет положительных оценок в тестовой выборке!
Пользователь 22366 не имеет положительных оценок в тестовой выборке!
Пользователь 8413 не имеет положительных оценок в тестовой выборке!
Пользователь 24970 не имеет положительных оценок в тестовой выборке!
Пользователь 44378 не имеет положительных оценок в тестовой выборке!
Пользователь 4681 не имеет положительных оценок в тестовой выборке!
Пользователь 4158 не имеет положительных оценок в тестовой выборке!
Пользователь 2083 не имеет положительных оценок в тестовой выборке!
Пользователь 9275 не имеет положительных оценок в тестовой выборке!
Пользователь 17241 не имеет положительных оценок в тестовой выборке!
Пользователь 41428 не имеет положительных оценок в тестовой выборке!
Пользователь 12588 не имеет положительных оценок в тестовой выборке!
Пользователь 42578 не имеет положительных оценок в тестовой выборке!
Пользователь 42979 не имеет положительных оценок в тестовой выборке!
Пользователь 20916 не имеет положительных оценок в тестовой выборке!
Пользователь 49292 не имеет положительных оценок в тестовой выборке!
Пользователь 38959 не имеет положительных оценок в тестовой выборке!
Пользователь 40790 не имеет положительных оценок в тестовой выборке!
Пользователь 18065 не имеет положительных оценок в тестовой выборке!
Пользователь 48054 не имеет положительных оценок в тестовой выборке!
Пользователь 7020 не имеет положительных оценок в тестовой выборке!
Пользователь 33854 не имеет положительных оценок в тестовой выборке!
Пользователь 780 не имеет положительных оценок в тестовой выборке!
Пользователь 3931 не имеет положительных оценок в тестовой выборке!

In [20]:
mean_popular_ap_at_10 = np.mean(popular_baseline_map10)
print(f"Среднее значение AP@10 для бейзлайна из популярных книг: {mean_popular_ap_at_10}")

Среднее значение AP@10 для бейзлайна из популярных книг: 0.012653061224489797

### Задание 3. Применение метода матричной факторизации и улучшение параметров алгоритма факторизации

In [41]:
user_id = train_user_index[user_index]

In [42]:
# Создание модели ALS
model = implicit.als.AlternatingLeastSquares(factors=64, iterations=30)

model.fit(sparse.csr_matrix(train_matrix), show_progress=True)

# Получаем рекомендации для пользователя
recommendations = model.recommend(user_index, sparse.csr_matrix(train_matrix)[user_index], N=20)

# Преобразуем индексы рекомендаций в book_id
recommended_book_ids = train_book_index[recommendations[0]]

# Выводим рекомендации
print(f"Рекомендации для пользователя {user_id}:")
for book_id in recommended_book_ids:
    print(f"- {book_id}")

  0%|          | 0/30 [00:00<?, ?it/s]

Рекомендации для пользователя 4:
- 133
- 50
- 59
- 117
- 80
- 76
- 15
- 171
- 114
- 241
- 70
- 278
- 90
- 230
- 48
- 740
- 77
- 100
- 26
- 150

In [45]:
from tqdm import tqdm

In [46]:
# Расчет mAP@10
als_map10 = []
for rand_user_ind in tqdm(random_users_inds):  # Используем tqdm для прогрессбара
    user_id = train_user_index[rand_user_ind]
    true_positives = test[test.user_id == user_id][test.rating == 1].book_id.tolist()

    if true_positives:
        recommendations = model.recommend(rand_user_ind, sparse.csr_matrix(train_matrix)[rand_user_ind], N=20)
        recommended_book_ids = train_book_index[recommendations[0]]
        ap10 = ap_at_k(recommended_book_ids, true_positives, k=10)
        als_map10.append(ap10)

100%|████████████████████████████████████████| 500/500 [10:47<00:00,  1.30s/it]

In [47]:
mean_als_ap_at_10 = np.mean(als_map10)
print(f"Среднее значение AP@10 для ALS: {mean_als_ap_at_10}")

# Сравнение с бейзлайнами
if mean_als_ap_at_10 > mean_popular_ap_at_10 and mean_als_ap_at_10 > mean_ap_at_10:
    print("ALS превзошел оба бейзлайна!")
elif mean_als_ap_at_10 > mean_popular_ap_at_10:
    print("ALS превзошел бейзлайн из популярных книг!")
elif mean_als_ap_at_10 > mean_ap_at_10:
    print("ALS превзошел случайный бейзлайн!")
else:
    print("ALS не превзошел ни один из бейзлайнов.")

Среднее значение AP@10 для ALS: 0.022540983606557378
ALS превзошел оба бейзлайна!

In [49]:
# Разные варианты параметров ALS
for factors in [200, 500]:
    for iterations in [20, 50]:
        print(f"Factors: {factors}, Iterations: {iterations}")
        # Обучаем ALS
        als = implicit.als.AlternatingLeastSquares(factors=factors, regularization=0.01, iterations=iterations)
        als.fit(sparse.csr_matrix(train_matrix), show_progress=True)

        # Расчет mAP@10
        als_map10 = []
        for rand_user_ind in tqdm(random_users_inds):  # Используем tqdm для прогрессбара
            user_id = train_user_index[rand_user_ind]
            true_positives = test[test.user_id == user_id][test.rating == 1].book_id.tolist()
        
            if true_positives:
                recommendations = model.recommend(rand_user_ind, sparse.csr_matrix(train_matrix)[rand_user_ind], N=20)
                recommended_book_ids = train_book_index[recommendations[0]]
                ap10 = ap_at_k(recommended_book_ids, true_positives, k=10)
                als_map10.append(ap10)

        mean_als_ap_at_10 = np.mean(als_map10)
        print(f"Среднее значение AP@10 для ALS: {mean_als_ap_at_10}")

        # Сравнение с бейзлайнами
        if mean_als_ap_at_10 > mean_popular_ap_at_10 and mean_als_ap_at_10 > mean_ap_at_10:
            print("ALS превзошел оба бейзлайна!")
        elif mean_als_ap_at_10 > mean_popular_ap_at_10:
            print("ALS превзошел бейзлайн из популярных книг!")
        elif mean_als_ap_at_10 > mean_ap_at_10:
            print("ALS превзошел случайный бейзлайн!")
        else:
            print("ALS не превзошел ни один из бейзлайнов.")
        print("-" * 20)  # Разделитель между вариантами параметров

Factors: 200, Iterations: 20

  0%|          | 0/20 [00:00<?, ?it/s]

100%|████████████████████████████████████████| 500/500 [10:47<00:00,  1.30s/it]

Среднее значение AP@10 для ALS: 0.022540983606557378
ALS превзошел оба бейзлайна!
--------------------
Factors: 200, Iterations: 50

  0%|          | 0/50 [00:00<?, ?it/s]

100%|████████████████████████████████████████| 500/500 [10:47<00:00,  1.29s/it]

Среднее значение AP@10 для ALS: 0.022540983606557378
ALS превзошел оба бейзлайна!
--------------------
Factors: 500, Iterations: 20

  0%|          | 0/20 [00:00<?, ?it/s]

100%|████████████████████████████████████████| 500/500 [10:46<00:00,  1.29s/it]

Среднее значение AP@10 для ALS: 0.022540983606557378
ALS превзошел оба бейзлайна!
--------------------
Factors: 500, Iterations: 50

  0%|          | 0/50 [00:00<?, ?it/s]

100%|████████████████████████████████████████| 500/500 [10:47<00:00,  1.30s/it]

Среднее значение AP@10 для ALS: 0.022540983606557378
ALS превзошел оба бейзлайна!
--------------------